export const current = {
  name: '@wrkspce',
  configType: 'project',
  children: [
    {
      name: 'assistance-feature-project',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-feature-project',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/feature/project',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=assistance-feature-project --bundler=rollup --directory=libs/assistance/feature/project --importPath=@wrkspce/assistance/feature/project --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [
        'assistance-ui-stocks',
        'assistance-feature-ai',
        'shared-ui',
        'shared-feature-diagram',
        'shared-util',
        'assistance-util',
        'shared-feature-form',
      ],
    },
    {
      name: 'assistance-feature-persona',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-feature-persona',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/feature/persona',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=assistance-feature-persona --bundler=rollup --directory=libs/assistance/feature/persona --importPath=@wrkspce/assistance/feature/persona --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [
        'shared-util',
        'shared-feature-avatar',
        'assistance-feature-ai',
        'assistance-util',
        'shared-ui',
        'assistance-ui-persona',
      ],
    },
    {
      name: 'assistance-feature-stocks',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-feature-stocks',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/feature/stocks',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=assistance-feature-stocks --bundler=rollup --directory=libs/assistance/feature/stocks --importPath=@wrkspce/assistance/feature/stocks --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [
        'assistance-ui-stocks',
        'assistance-feature-ai',
        'shared-util',
      ],
    },
    {
      name: 'assistance-ui-project',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-ui-project',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'ui',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/ui/project',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/react:library --name=assistance-ui-project --bundler=rollup --directory=libs/assistance/ui/project --importPath=@wrkspce/assistance/ui/project --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:ui" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [],
    },
    {
      name: 'shared-feature-diagram',
      configType: 'library',
      scope: 'shared',
      fields: [
        {
          name: 'name',
          value: 'shared-feature-diagram',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'shared',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/shared/feature/diagram',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=shared-feature-diagram --bundler=rollup --directory=libs/shared/feature/diagram --importPath=@wrkspce/shared/feature/diagram --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:shared, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [],
    },
    {
      name: 'assistance-feature-ai',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-feature-ai',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/feature/ai',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=assistance-feature-ai --bundler=rollup --directory=libs/assistance/feature/ai --importPath=@wrkspce/assistance/feature/ai --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: ['assistance-util'],
    },
    {
      name: 'assistance-ui-persona',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-ui-persona',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'ui',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/ui/persona',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/react:library --name=assistance-ui-persona --bundler=rollup --directory=libs/assistance/ui/persona --importPath=@wrkspce/assistance/ui/persona --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:ui" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: ['shared-feature-avatar'],
    },
    {
      name: 'shared-feature-avatar',
      configType: 'library',
      scope: 'shared',
      fields: [
        {
          name: 'name',
          value: 'shared-feature-avatar',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'shared',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/shared/feature/avatar',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=shared-feature-avatar --bundler=rollup --directory=libs/shared/feature/avatar --importPath=@wrkspce/shared/feature/avatar --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:shared, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [],
    },
    {
      name: 'assistance-ui-stocks',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-ui-stocks',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'ui',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/ui/stocks',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/react:library --name=assistance-ui-stocks --bundler=rollup --directory=libs/assistance/ui/stocks --importPath=@wrkspce/assistance/ui/stocks --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:ui" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: ['shared-ui', 'shared-util', 'assistance-feature-ai'],
    },
    {
      name: 'shared-feature-form',
      configType: 'library',
      scope: 'shared',
      fields: [
        {
          name: 'name',
          value: 'shared-feature-form',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'shared',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'feature',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/shared/feature/form',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:library --name=shared-feature-form --bundler=rollup --directory=libs/shared/feature/form --importPath=@wrkspce/shared/feature/form --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:shared, type:feature" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [],
    },
    {
      name: 'assistance-ui-chat',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-ui-chat',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'ui',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/ui/chat',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/react:library --name=assistance-ui-chat --bundler=rollup --directory=libs/assistance/ui/chat --importPath=@wrkspce/assistance/ui/chat --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:ui" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [
        'assistance-feature-ai',
        'shared-ui',
        'shared-feature-avatar',
      ],
    },
    {
      name: 'assistance-plugin',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-plugin',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'plugin',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/plugin/plugin',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/javascript:library --name=assistance-plugin --bundler=rollup --directory=libs/assistance/plugin/plugin --importPath=@wrkspce/assistance/plugin/plugin --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:plugin" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: ['assistance-feature-project'],
    },
    {
      name: 'assistance-util',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-util',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'util',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/util/util',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/javascript:library --name=assistance-util --bundler=rollup --directory=libs/assistance/util/util --importPath=@wrkspce/assistance/util/util --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:util" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [],
    },
    {
      name: 'assistance-app',
      configType: 'app',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-app',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'app',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/app/app',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/next:application --name=assistance-app --bundler=rollup --directory=libs/assistance/app/app --importPath=@wrkspce/assistance/app/app --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:app" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [
        'assistance-feature-stocks',
        'assistance-ui-chat',
        'assistance-feature-project',
        'shared-ui',
      ],
    },
    {
      name: 'assistance-e2e',
      configType: 'library',
      scope: 'assistance',
      fields: [
        {
          name: 'name',
          value: 'assistance-e2e',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'assistance',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'e2e',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/assistance/e2e/e2e',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/javascript:library --name=assistance-e2e --bundler=rollup --directory=libs/assistance/e2e/e2e --importPath=@wrkspce/assistance/e2e/e2e --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:assistance, type:e2e" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: ['assistance-app'],
    },
    {
      name: 'shared-util',
      configType: 'library',
      scope: 'shared',
      fields: [
        {
          name: 'name',
          value: 'shared-util',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'shared',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'util',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/shared/util/util',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/javascript:library --name=shared-util --bundler=rollup --directory=libs/shared/util/util --importPath=@wrkspce/shared/util/util --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:shared, type:util" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: [],
    },
    {
      name: 'shared-ui',
      configType: 'library',
      scope: 'shared',
      fields: [
        {
          name: 'name',
          value: 'shared-ui',
          required: true,
          type: 'input',
          label: 'Name',
        },
        {
          name: 'scope',
          value: 'shared',
          required: true,
          type: 'input',
          label: 'Scope',
        },
        {
          name: 'type',
          value: 'ui',
          required: true,
          type: 'input',
          label: 'Type',
        },
        {
          name: 'importPath',
          value: '@wrkspce/shared/ui/ui',
          required: true,
          type: 'input',
          label: 'Import Path',
        },
        {
          name: 'generatorScript',
          value:
            'nx g @nx/react:library --name=shared-ui --bundler=rollup --directory=libs/shared/ui/ui --importPath=@wrkspce/shared/ui/ui --projectNameAndRootFormat=as-provided --publishable=true --tags="scope:shared, type:ui" --unitTestRunner=jest',
          required: true,
          type: 'input',
          label: 'Generator Script',
        },
      ],
      dependencies: ['shared-util'],
    },
  ],
};

export const generator =
  "async function projectConfigurationGenerator(tree) {\n    const projectName = 'wrkspce';\n    const projects = (0, _devkit.readCachedProjectGraph)().nodes;\n    const { dependencies } = (0, _devkit.readCachedProjectGraph)();\n    const projectNames = Object.keys(projects);\n    const configuraton = {\n        name: '@wrkspce',\n        configType: 'project',\n        children: projectNames.filter((name)=>name !== 'project').map((projectName)=>{\n            const project = projects[projectName];\n            const projectDependencies = dependencies[projectName];\n            const projectScope = projectName.split('-')[0];\n            const projectType = projectName.split('-')[1];\n            const configType = project.type;\n            const importPath = `@${projectName}/${projectScope}/${projectType}/${projectName.split('-').pop()}`;\n            const generatorScript = `nx g @nx/${projectType === 'ui' ? 'react:library' : projectType === 'feature' ? 'next:library' : projectType === 'app' ? 'next:application' : 'javascript:library'} --name=${projectName} --bundler=rollup --directory=libs/${projectScope}/${projectType}/${projectName.split('-').pop()} --importPath=${importPath} --projectNameAndRootFormat=as-provided --publishable=true --tags=\"scope:${projectScope}, type:${projectType}\" --unitTestRunner=jest`;\n            return {\n                name: projectName,\n                configType: configType === 'app' ? 'app' : 'library',\n                scope: projectScope,\n                fields: [\n                    {\n                        name: 'name',\n                        value: projectName,\n                        required: true,\n                        type: 'input',\n                        label: 'Name'\n                    },\n                    {\n                        name: 'scope',\n                        value: projectScope,\n                        required: true,\n                        type: 'input',\n                        label: 'Scope'\n                    },\n                    {\n                        name: 'type',\n                        value: projectType,\n                        required: true,\n                        type: 'input',\n                        label: 'Type'\n                    },\n                    {\n                        name: 'importPath',\n                        value: importPath,\n                        required: true,\n                        type: 'input',\n                        label: 'Import Path'\n                    },\n                    {\n                        name: 'generatorScript',\n                        value: generatorScript,\n                        required: true,\n                        type: 'input',\n                        label: 'Generator Script'\n                    }\n                ],\n                dependencies: projectDependencies.filter((dependency)=>!dependency.target.includes('npm:')).map((dependency)=>dependency.target)\n            };\n        })\n    };\n    const graph = {\n        root: '@wrkspce',\n        apps: configuraton.children.filter((child)=>child.configType === 'app').map((child)=>({\n                name: child.name,\n                scope: child.scope,\n                dependencies: child.dependencies\n            })),\n        libs: configuraton.children.filter((child)=>child.configType === 'library').map((child)=>({\n                name: child.name,\n                scope: child.scope,\n                dependencies: child.dependencies\n            }))\n    };\n    const templatePath = _path.join(__dirname, 'files/src');\n    (0, _devkit.generateFiles)(tree, templatePath, 'libs/assistance/feature/project/src/lib/tools/generateProject', {\n        config: configuraton,\n        generator: projectConfigurationGenerator.toString(),\n        graph: graph\n    });\n    await (0, _devkit.formatFiles)(tree);\n}";

export const graph = {
  root: '@wrkspce',
  apps: [
    {
      name: 'assistance-app',
      scope: 'assistance',
      dependencies: [
        'assistance-feature-stocks',
        'assistance-ui-chat',
        'assistance-feature-project',
        'shared-ui',
      ],
    },
  ],
  libs: [
    {
      name: 'assistance-feature-project',
      scope: 'assistance',
      dependencies: [
        'assistance-ui-stocks',
        'assistance-feature-ai',
        'shared-ui',
        'shared-feature-diagram',
        'shared-util',
        'assistance-util',
        'shared-feature-form',
      ],
    },
    {
      name: 'assistance-feature-persona',
      scope: 'assistance',
      dependencies: [
        'shared-util',
        'shared-feature-avatar',
        'assistance-feature-ai',
        'assistance-util',
        'shared-ui',
        'assistance-ui-persona',
      ],
    },
    {
      name: 'assistance-feature-stocks',
      scope: 'assistance',
      dependencies: [
        'assistance-ui-stocks',
        'assistance-feature-ai',
        'shared-util',
      ],
    },
    { name: 'assistance-ui-project', scope: 'assistance', dependencies: [] },
    { name: 'shared-feature-diagram', scope: 'shared', dependencies: [] },
    {
      name: 'assistance-feature-ai',
      scope: 'assistance',
      dependencies: ['assistance-util'],
    },
    {
      name: 'assistance-ui-persona',
      scope: 'assistance',
      dependencies: ['shared-feature-avatar'],
    },
    { name: 'shared-feature-avatar', scope: 'shared', dependencies: [] },
    {
      name: 'assistance-ui-stocks',
      scope: 'assistance',
      dependencies: ['shared-ui', 'shared-util', 'assistance-feature-ai'],
    },
    { name: 'shared-feature-form', scope: 'shared', dependencies: [] },
    {
      name: 'assistance-ui-chat',
      scope: 'assistance',
      dependencies: [
        'assistance-feature-ai',
        'shared-ui',
        'shared-feature-avatar',
      ],
    },
    {
      name: 'assistance-plugin',
      scope: 'assistance',
      dependencies: ['assistance-feature-project'],
    },
    { name: 'assistance-util', scope: 'assistance', dependencies: [] },
    {
      name: 'assistance-e2e',
      scope: 'assistance',
      dependencies: ['assistance-app'],
    },
    { name: 'shared-util', scope: 'shared', dependencies: [] },
    { name: 'shared-ui', scope: 'shared', dependencies: ['shared-util'] },
  ],
};
